// ─────────────────────────────────────────────────────────────
// ACCESS ALGO – 8+9
// © Hc_Sunt_Lucrum | access-algo.com
// This script is subject to the terms of the Mozilla Public License 2.0
// https://mozilla.org/MPL/2.0/
//
// Description:
// Overbought and oversold 8+9 candle detection. Shows signs of reversals. 
//
// Usage:anyone
// Designed for TradingView. Compatible with Pine Script v6.
// Free to use under invite-only rules or for educational purposes.
//
// Version:         v1
// Last Updated:    2025-04-17
// Author:          Hc_Sunt_Lucrum
// Contact:         access-algo.com | TradingView: @Hc_Sunt_Lucrum
// ─────────────────────────────────────────────────────────────
// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © hc_svnt_mordacitas

//@version=6

indicator(title = 'TD 8 + 9', shorttitle = 'TD 8 + 9', overlay = true, timeframe = '')

// // TURN TD 8's & 9's ON / OFF ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

showBuyTDs = input(true, title = 'Show TD Buy')
showSellTDs = input(true, title = 'Show TD Sell')


// // TD CALCS /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

buySignals = 0
buySignals := close < close[4] ? buySignals[1] == 9 ? 1 : buySignals[1] + 1 : 0

sellSignals = 0
sellSignals := close > close[4] ? sellSignals[1] == 9 ? 1 : sellSignals[1] + 1 : 0

BuyOrSell = math.max(buySignals, sellSignals)

TD8buy = showBuyTDs and bool(buySignals) and BuyOrSell == 8
TD9buy = showBuyTDs and bool(buySignals) and BuyOrSell == 9

TD8sell = showSellTDs and bool(sellSignals) and BuyOrSell == 8
TD9sell = showSellTDs and bool(sellSignals) and BuyOrSell == 9

// TD LABELS /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

plotshape(TD8buy, style = shape.labelup, text = '8', color = color.new(color.green, 0), textcolor = color.new(color.white, 0), size = size.tiny, location = location.belowbar)
plotshape(TD9buy, style = shape.labelup, text = '9', color = color.new(color.green, 0), textcolor = color.new(color.white, 0), size = size.tiny, location = location.belowbar)
plotshape(TD8sell, style = shape.labeldown, text = '8', color = color.new(color.red, 0), textcolor = color.new(color.white, 0), size = size.tiny, location = location.abovebar)
plotshape(TD9sell, style = shape.labeldown, text = '9', color = color.new(color.red, 0), textcolor = color.new(color.white, 0), size = size.tiny, location = location.abovebar)


// ALERTS /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

alertcondition(TD8buy, 'TD 8 Buy', 'TD 8 Buy') // Once per bar close
alertcondition(TD9buy, 'TD 9 Buy', 'TD 9 Buy') // Once per bar close
alertcondition(TD8sell, 'TD 8 Sell', 'TD 8 Sell') // Once per bar close
alertcondition(TD9sell, 'TD 9 Sell', 'TD 9 Sell') // Once per bar close
