// ─────────────────────────────────────────────────────────────
// ACCESS ALGO – Short Pullback
// © Hc_Sunt_Lucrum | access-algo.com
// This script is subject to the terms of the Mozilla Public License 2.0
// https://mozilla.org/MPL/2.0/
//
// Description:When the fast MA crosses the Slow, a Green buy or a Red Sell triangle is printed on a bandwidth pullback touch
// 
//
// Usage:
// Designed for TradingView. Compatible with Pine Script v6.
// Free to use under invite-only rules or for educational purposes.
//
// Version:         v5
// Last Updated:    2025-04-16
// Author:          Hc_Sunt_Lucrum
// Contact:         access-algo.com | TradingView: @Hc_Sunt_Lucrum
// ─────────────────────────────────────────────────────────────
// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © hc_svnt_mordacitas

//@version=5
indicator("Short-Pullback", shorttitle="Short Pullback", overlay=true)

//Moving Averages
sma8 = ta.sma(close, 8)
sma20 = ta.sma(close, 20)

//Bands
ema5Low = ta.ema(low, 6)
ema5High = ta.ema(high, 6)

//Crosses
crossAbove = ta.crossover(sma8, sma20)
crossBelow = ta.crossunder(sma8, sma20)

//Logic for the signals
var lookingForGreenTriangle = false
var greenTrianglePlotted = false
if crossAbove
    lookingForGreenTriangle := true
    greenTrianglePlotted := false

plotGreenTriangle = lookingForGreenTriangle and not greenTrianglePlotted and low < ema5Low and sma8 > sma20
if plotGreenTriangle
    greenTrianglePlotted := true
    lookingForGreenTriangle := false

var lookingForRedTriangle = false
var redTrianglePlotted = false
if crossBelow
    lookingForRedTriangle := true
    redTrianglePlotted := false

plotRedTriangle = lookingForRedTriangle and not redTrianglePlotted and high > ema5High and sma8 < sma20
if plotRedTriangle
    redTrianglePlotted := true
    lookingForRedTriangle := false

// Plot to chart
plot(sma8, color=color.gray, title="8 SMA", linewidth=1)
plot(sma20, color=color.blue, title="20 SMA", linewidth=1)
plot(ema5Low, color=color.red, title="5 EMA Low", linewidth=1)
plot(ema5High, color=color.red, title="5 EMA High", linewidth=1)

// Plotting Shapes
plotshape(series=plotGreenTriangle, location=location.belowbar, color=color.green, style=shape.triangleup, size=size.normal, title="Green Triangle")
plotshape(series=crossAbove, location=location.belowbar, color=color.green, style=shape.xcross, size=size.normal, title="Green Cross")
plotshape(series=plotRedTriangle, location=location.abovebar, color=color.red, style=shape.triangledown, size=size.normal, title="Red Triangle")
plotshape(series=crossBelow, location=location.abovebar, color=color.red, style=shape.xcross, size=size.normal, title="Red Cross")
