// ─────────────────────────────────────────────────────────────
// ACCESS ALGO – Time Session Filter
// © Hc_Sunt_Lucrum | access-algo.com
// This script is subject to the terms of the Mozilla Public License 2.0
// https://mozilla.org/MPL/2.0/
//
// Description: Correct code to use for timeframe shown on the chart. Also good use for filter in strategy code. 
// 
//
// Usage:
// Designed for TradingView. Compatible with Pine Script v6.
// Free to use under invite-only rules or for educational purposes.
//
// Version:         v1
// Last Updated:    2025-06-03
// Author:          Hc_Sunt_Lucrum
// Contact:         access-algo.com | TradingView: @Hc_Sunt_Lucrum
// ─────────────────────────────────────────────────────────────// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © hc_svnt_mordacitas

//@version=5

indicator("Time Session", overlay=true)

session = input.session(title="Time Session to Highlight", defval="0900-1800")

isInSession(_sess) => not na(time(timeframe.period, _sess))

bgcolor(isInSession(session) ? color.new(color.red,75) : na)

plot(close)
